-- Customer
INSERT INTO "PUBLIC"."CUSTOMER" ("CUSTOMER_ID", "EMAIL", "FIRST_NAME", "JOINED", "LAST_NAME")
    VALUES (1, 'john.citizen@email.com', 'John', '1970-01-14 02:29:07', 'Citizen');

-- Basket
INSERT INTO "PUBLIC"."BASKET" ("BASKET_ID", "CUSTOMER_ID")
    VALUES (1, 1);

-- Products
INSERT INTO "PUBLIC"."PRODUCT" ("NAME", "PRODUCT_ID")
    VALUES ('Fender Telecaster', 1);
INSERT INTO "PUBLIC"."PRODUCT" ("NAME", "PRODUCT_ID")
    VALUES ('Fender Jazzmaster', 2);

-- Attributes
INSERT INTO "PUBLIC"."ATTRIBUTE" ("ATTRIBUTE_ID", "NAME", "PRODUCT_ID")
    VALUES (1, 'Neck', 1);
INSERT INTO "PUBLIC"."ATTRIBUTE" ("ATTRIBUTE_ID", "NAME", "PRODUCT_ID")
    VALUES (2, 'Colour', 1);
INSERT INTO "PUBLIC"."ATTRIBUTE" ("ATTRIBUTE_ID", "NAME", "PRODUCT_ID")
    VALUES (3, 'Neck', 2);
INSERT INTO "PUBLIC"."ATTRIBUTE" ("ATTRIBUTE_ID", "NAME", "PRODUCT_ID")
    VALUES (4, 'Colour', 2);
    
-- Values
INSERT INTO "PUBLIC"."VALUE" ("ATTRIBUTE_ID", "NAME", "VALUE_ID")
    VALUES (1, 'Rosewood', 1);
INSERT INTO "PUBLIC"."VALUE" ("ATTRIBUTE_ID", "NAME", "VALUE_ID")
    VALUES (1, 'Maple', 2);
INSERT INTO "PUBLIC"."VALUE" ("ATTRIBUTE_ID", "NAME", "VALUE_ID")
    VALUES (2, 'Candy Apple Red', 3);
INSERT INTO "PUBLIC"."VALUE" ("ATTRIBUTE_ID", "NAME", "VALUE_ID")
    VALUES (2, 'Sonic Blue', 4);
INSERT INTO "PUBLIC"."VALUE" ("ATTRIBUTE_ID", "NAME", "VALUE_ID")
    VALUES (3, 'Rosewood', 5);
INSERT INTO "PUBLIC"."VALUE" ("ATTRIBUTE_ID", "NAME", "VALUE_ID")
    VALUES (3, 'Maple', 6);
INSERT INTO "PUBLIC"."VALUE" ("ATTRIBUTE_ID", "NAME", "VALUE_ID")
    VALUES (4, 'Fiesta Red', 7);
INSERT INTO "PUBLIC"."VALUE" ("ATTRIBUTE_ID", "NAME", "VALUE_ID")
    VALUES (4, 'Lake Placid Blue', 8);

-- SKUs (e.g. possible products)
-- Telecasters
INSERT INTO "PUBLIC"."STOCK_KEEPING_UNIT" ("NAME", "PRICE", "PRODUCT_ID", "SKU_ID")
    VALUES ('Fender Telecaster (Rosewood neck, Candy Apple Red)', 1139.99, 1, 1);
INSERT INTO "PUBLIC"."STOCK_KEEPING_UNIT" ("NAME", "PRICE", "PRODUCT_ID", "SKU_ID")
    VALUES ('Fender Telecaster (Rosewood neck, Sonic Blue)', 1139.99, 1, 2);
INSERT INTO "PUBLIC"."STOCK_KEEPING_UNIT" ("NAME", "PRICE", "PRODUCT_ID", "SKU_ID")
    VALUES ('Fender Telecaster (Maple neck, Candy Apple Red)', 1019.99, 1, 3);
INSERT INTO "PUBLIC"."STOCK_KEEPING_UNIT" ("NAME", "PRICE", "PRODUCT_ID", "SKU_ID")
    VALUES ('Fender Telecaster (Maple neck, Sonic Blue)', 1019.99, 1, 4);
    
-- Jazzmasters
INSERT INTO "PUBLIC"."STOCK_KEEPING_UNIT" ("NAME", "PRICE", "PRODUCT_ID", "SKU_ID")
    VALUES ('Fender Jazzmaster (Rosewood neck, Fiesta Red)', 1199.99, 2, 5);
INSERT INTO "PUBLIC"."STOCK_KEEPING_UNIT" ("NAME", "PRICE", "PRODUCT_ID", "SKU_ID")
    VALUES ('Fender Jazzmaster (Rosewood neck, Lake Placid Blue)', 1199.99, 2, 6);   
INSERT INTO "PUBLIC"."STOCK_KEEPING_UNIT" ("NAME", "PRICE", "PRODUCT_ID", "SKU_ID")
    VALUES ('Fender Jazzmaster (Maple neck, Fiesta Red)', 1099.99, 2, 7);
INSERT INTO "PUBLIC"."STOCK_KEEPING_UNIT" ("NAME", "PRICE", "PRODUCT_ID", "SKU_ID")
    VALUES ('Fender Jazzmaster (Maple neck, Lake Placid Blue)', 1099.99, 2, 8);
    
-- SKU to attribute values mapping
-- Telecasters (Maple)
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (1, 1);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (1, 3);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (2, 1);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (2, 4);
-- Telecasters (Rosewood)
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (3, 2);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (3, 3);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (4, 2);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (4, 4);
-- Jazzmasters (Maple)
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (5, 5);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (5, 7);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (6, 5);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (6, 8);
-- Jazzmasters (Rosewood)
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (7, 6);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (7, 7);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (8, 6);
INSERT INTO "PUBLIC"."PRODUCT_VARIANT" ("SKU_ID", "VALUE_ID")
    VALUES (8, 8);
    
-- Actual, in stock items
INSERT INTO "PUBLIC"."INVENTORY" ("CREATED", "INVENTORY_ID", "LABEL", "SKU_ID", )
    VALUES ('1970-02-02 08:38:01', 1, '7be997ca-79d3-495e-9577-9d3f4c755372', 1, );
INSERT INTO "PUBLIC"."INVENTORY" ("CREATED", "INVENTORY_ID", "LABEL", "SKU_ID", )
    VALUES ('1970-02-02 08:38:01', 2, 'c7e5c62a-ae23-4d5f-8e0f-6a6b3e576e42', 2, );

-- Things in baskets
INSERT INTO "PUBLIC"."BASKET_ITEM" ("ADDED", "BASKET_ID", "BASKET_ITEM_ID", "INVENTORY_ID", "SAVE_FOR_LATER")
    VALUES ('1970-04-19 04:25:39', 1, 1, 1, true);

